### ISSUE TITLE
Sbt compile does not create jarfile rehearsal.jar in target/scala-2.11/

### ISSUE THREAD

**Issue by akondrahman** [plasma-umass/Rehearsal#2]
I was replicating the Vagrant process stated in the project README. While running the benchmarks, I am stuck with this error: ERROR: Error: Unable to access jarfile target/scala-2.11/rehearsal.jar 

Apparently the required jar file i.e. rehearsal.jar is not created in target/scala-2.11/. 

Any help will be appreciated.  

I am using Vagrant 1.8.1 on a MacOS 10.11.6

**Comment by arjunguha** [comment]
Hi,

Thanks for your interest. I'm surprised that you had this issue, since the jarFile is specified in build.sbt. Would you paste in your terminal-interaction here and I'll try to see what went wrong.

**Comment by akondrahman** [comment]
Thanks. Here goes the commands 

vagrant up --provider virtualbox
vagrant ssh 
cd /vagrant/
sbt compile 
cd results
make all  ####[While executing this step, I get the following error]####
Error message (full):
(cd ..; scala scripts/Benchmarks.scala idempotence 10 results/idempotence.csv)
Name, Time
ERROR: Error: Unable to access jarfile target/scala-2.11/rehearsal.jar
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at Main$$anon$6$$anon$4.bench(Benchmarks.scala:188)
	at Main$$anon$6$$anon$4$$anonfun$1.apply$mcVI$sp(Benchmarks.scala:193)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at Main$$anon$6$$anon$4.<init>(Benchmarks.scala:192)
	at Main$$anon$6.doIdempotence(Benchmarks.scala:176)
	at Main$$anon$6.<init>(Benchmarks.scala:237)
	at Main$.main(Benchmarks.scala:1)
	at Main.main(Benchmarks.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:175)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1$$anonfun$apply$mcZ$sp$1.apply(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
	at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:205)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:67)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
make: *** [idempotence.csv] Error 1

**Comment by arjunguha** [comment]
I think we have an issue in the directions, instead of `sbt compile` try `sbt assembly`. Let me know how that goes.

**Comment by arjunguha** [comment]
Also, I'm sorry I didn't notice this issue earlier: I just realized you created it nine days ago!

**Comment by akondrahman** [comment]
I tried `sbt assembly`. After performing `sbt assembly`, I did` make all` in `/results`. 

Now,  I am getting another exception, which seems to be related to a file being missing. 

##Raw exception error message##
ERROR: Exception in thread "main" java.nio.file.NoSuchFileException: parser-tests/good/dhoppe-monit.pp
ERROR: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
ERROR: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
ERROR: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
ERROR: 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
ERROR: 	at java.nio.file.Files.newByteChannel(Files.java:361)
ERROR: 	at java.nio.file.Files.newByteChannel(Files.java:407)
ERROR: 	at java.nio.file.Files.readAllBytes(Files.java:3152)
ERROR: 	at rehearsal.PuppetParser$.parseFile(PuppetParser.scala:213)
ERROR: 	at rehearsal.Main$.idempotenceBenchmark(Main.scala:43)
ERROR: 	at rehearsal.Main$$anon$1$$anonfun$10$$anonfun$apply$4.apply(Main.scala:195)
ERROR: 	at rehearsal.Main$$anon$1$$anonfun$10$$anonfun$apply$4.apply(Main.scala:195)
ERROR: 	at rehearsal.Main$.delayedEndpoint$rehearsal$Main$1(Main.scala:217)
ERROR: 	at rehearsal.Main$delayedInit$body.apply(Main.scala:5)
ERROR: 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
ERROR: 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
ERROR: 	at scala.App$$anonfun$main$1.apply(App.scala:76)
ERROR: 	at scala.App$$anonfun$main$1.apply(App.scala:76)
ERROR: 	at scala.collection.immutable.List.foreach(List.scala:381)
ERROR: 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
ERROR: 	at scala.App$class.main(App.scala:76)
ERROR: 	at rehearsal.Main$.main(Main.scala:5)
ERROR: 	at rehearsal.Main.main(Main.scala)
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at Main$$anon$6$$anon$4.bench(Benchmarks.scala:188)
	at Main$$anon$6$$anon$4$$anonfun$1.apply$mcVI$sp(Benchmarks.scala:193)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at Main$$anon$6$$anon$4.<init>(Benchmarks.scala:192)
	at Main$$anon$6.doIdempotence(Benchmarks.scala:176)
	at Main$$anon$6.<init>(Benchmarks.scala:237)
	at Main$.main(Benchmarks.scala:1)
	at Main.main(Benchmarks.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:175)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1$$anonfun$apply$mcZ$sp$1.apply(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
	at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:192)
	at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:205)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:67)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

**Comment by arjunguha** [comment]
Ah, this is because some third-party code is in a separate, private repository. I'll send it over email.

**Comment by akondrahman** [comment]
Thanks professor. 

Unfortunately while running the command `scala scripts/Benchmarks.scala determinism 10 results/determinism.csv` I get a `ERROR: Exception in thread "main" rehearsal.Unexpected: ')' expected but 'S' found` error. Any ideas? The full error stack is given below: 

ERROR: Exception in thread "main" rehearsal.Unexpected: `)' expected but `S' found
ERROR: 	at rehearsal.Datalog$MitreDatalog.eval(Datalog.scala:53)
ERROR: 	at rehearsal.Datalog$Evaluator.eval(Datalog.scala:175)
ERROR: 	at rehearsal.PuppetEval$.eval(PuppetEval.scala:561)
ERROR: 	at rehearsal.PuppetSyntax$Manifest$class.eval(PuppetSyntax.scala:51)
ERROR: 	at rehearsal.PuppetSyntax$MSeq.eval(PuppetSyntax.scala:55)
ERROR: 	at rehearsal.Main$.determinismBenchmark(Main.scala:58)
ERROR: 	at rehearsal.Main$$anon$1$$anonfun$11$$anonfun$apply$5.apply(Main.scala:200)
ERROR: 	at rehearsal.Main$$anon$1$$anonfun$11$$anonfun$apply$5.apply(Main.scala:200)
ERROR: 	at rehearsal.Main$.delayedEndpoint$rehearsal$Main$1(Main.scala:217)
ERROR: 	at rehearsal.Main$delayedInit$body.apply(Main.scala:5)
ERROR: 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
ERROR: 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
ERROR: 	at scala.App$$anonfun$main$1.apply(App.scala:76)
ERROR: 	at scala.App$$anonfun$main$1.apply(App.scala:76)
ERROR: 	at scala.collection.immutable.List.foreach(List.scala:381)
ERROR: 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
ERROR: 	at scala.App$class.main(App.scala:76)
ERROR: 	at rehearsal.Main$.main(Main.scala:5)
ERROR: 	at rehearsal.Main.main(Main.scala)

**Comment by arjunguha** [comment]
Odd. Can you run the test suite "sbt test"?

**Comment by akondrahman** [comment]
Ran sbt test. Here is the output: 


[info] ScalaTest
[info] Run completed in 8 seconds, 263 milliseconds.
[info] Total number of tests run: 116
[info] Suites: completed 5, aborted 2
[info] Tests: succeeded 3, failed 113, canceled 0, ignored 0, pending 0
[info] *** 2 SUITES ABORTED ***
[info] *** 113 TESTS FAILED ***
[error] Error: Total 118, Failed 113, Errors 2, Passed 3
[error] Failed tests:
[error] 	DeterminismEvaluationSuite
[error] 	CommutativityTests
[error] 	SymbolicEvaluatorTests
[error] 	PredicateTests
[error] 	IdempotenceEvaluationSuite
[error] Error during tests:
[error] 	SimpleParserTests
[error] 	SimpleEvalTests

**Comment by arjunguha** [comment]
Figured it out:

https://github.com/plasma-umass/Rehearsal/commit/3c199fe86a654a15350b38f1caaddbff92c977be

On your VM, you should delete and reinstall Datalog. However, between the `./configure` and `make` commands, you should run the following to not link to readline:

```
sed -i "s/-DHAVE_LIBREADLINE=1//g" Makefile
```

**Comment by arjunguha** [comment]
@akondrahman were you able to resolve this?

**Comment by arjunguha** [comment]
Closing this issue for now.
